## 1단계 문제

In [3]:
import numpy as np

1. 크기가 10인 null 벡터를 만드세요. (힌트: np.zeros())

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. numpy 버전과 설정을 출력하세요. (힌트: np.__version__, np.show_config())

In [5]:
np.__version__

'2.3.0'

In [7]:
# np.show_config()

3. 값이 10에서 49까지인 벡터를 만드세요. (힌트: np.arange(10, 50))

In [10]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. 벡터를 역순으로 만드세요 (첫 번째 요소가 마지막이 됩니다). (힌트: 배열을 뒤집기 위해 [::-1])

In [11]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5. 크기가 3x3이고 0에서 8까지의 값을 갖는 행렬을 만드세요. (힌트: np.arange()와 reshape())

In [12]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 2단계 문제

1. 1D 배열을 3x3 행렬로 변환하세요. (힌트: reshape())

In [13]:
arr1 = np.arange(9)
arr1.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2. 0에서 1 사이의 랜덤한 값으로 채워진 3x3 배열을 만드세요. (힌트: np.random.random())

In [21]:
np.random.random((3, 3))

array([[0.47006846, 0.51225737, 0.92121248],
       [0.54710763, 0.14062232, 0.75330664],
       [0.90062229, 0.19654729, 0.8776547 ]])

3. 5x5 단위 행렬을 만드세요. (힌트: np.eye(5))

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4. 임의의 1D 배열에서 가장 큰 값의 인덱스를 찾으세요. (힌트: np.argmax())

In [72]:
arr2 = np.random.choice(20, size=5, replace=False)
arr2

array([ 7,  6, 18, 17, 12], dtype=int32)

In [73]:
np.argmax(arr2)

np.int64(2)

5. 크기가 10인 배열을 생성하고, 3에서 8까지의 값을 0으로 바꾸세요. (힌트: 슬라이싱과 배열 인덱싱)

In [26]:
arr3 = np.arange(10)
arr3[3:9] = 0
arr3

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 9])

## 3단계 문제

1. 임의의 배열에서 가장 작은 값과 가장 큰 값을 교환하세요. (힌트: np.min(), np.max()와 인덱싱)

In [66]:
arr4 = np.random.choice(20, size=5, replace=False)
arr4

array([15,  7,  2,  3, 19], dtype=int32)

In [69]:
arr4_min = np.min(arr4)
min_idx = np.argmin(arr4)

In [70]:
arr4_max = np.max(arr4)
max_idx = np.argmax(arr4)

In [71]:
arr4[max_idx] = arr4_min
arr4[min_idx] = arr4_max
arr4

array([15,  7, 19,  3,  2], dtype=int32)

2. 3차원 배열의 각 슬라이스마다 평균값을 계산하세요. (힌트: np.mean()과 축 설정)

In [46]:
arr5 = np.arange(27).reshape(3, 3, 3)
print(arr5)
np.mean(arr5, axis=(1, 2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 4., 13., 22.])

3. 크기가 100인 배열을 생성하고 평균, 표준편차를 계산하세요. (힌트: np.mean(), np.std())

In [48]:
arr6 = np.arange(100)
print(np.mean(arr6))
print(np.std(arr6))

49.5
28.86607004772212


4. 주어진 2D 배열에서 고유한 행을 찾으세요. (힌트: np.unique()와 axis 설정)

In [65]:
arr7 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6],
    [0, 0, 0]
])

np.unique(arr7, axis=0)

array([[0, 0, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

5. 임의의 10x10 배열에서 가장 큰 값 5개를 찾으세요. (힌트: np.argsort()와 슬라이싱)

In [61]:
arr8 = np.random.choice(100, size=(10, 10), replace=False)
arr8

array([[26, 84, 47,  5, 69, 81, 63, 65, 33, 46],
       [41, 89, 42, 29, 21, 48, 36, 90, 51, 92],
       [49, 53, 73, 85, 50, 30, 13, 32, 56, 77],
       [68,  8, 94, 58,  1, 54, 15, 23, 52, 70],
       [ 3, 82,  6, 37, 75,  9, 22, 12, 71, 39],
       [76, 57, 80, 17, 45, 20, 64, 35, 87, 78],
       [99, 19,  0, 24, 34, 79, 61, 31, 59, 83],
       [14, 10, 66, 28, 97, 98, 25, 60, 88, 93],
       [96, 86,  7, 44, 74, 67, 62, 43, 72, 95],
       [38,  4, 11, 18, 91,  2, 40, 27, 55, 16]], dtype=int32)

In [64]:
arr8.flatten()

array([26, 84, 47,  5, 69, 81, 63, 65, 33, 46, 41, 89, 42, 29, 21, 48, 36,
       90, 51, 92, 49, 53, 73, 85, 50, 30, 13, 32, 56, 77, 68,  8, 94, 58,
        1, 54, 15, 23, 52, 70,  3, 82,  6, 37, 75,  9, 22, 12, 71, 39, 76,
       57, 80, 17, 45, 20, 64, 35, 87, 78, 99, 19,  0, 24, 34, 79, 61, 31,
       59, 83, 14, 10, 66, 28, 97, 98, 25, 60, 88, 93, 96, 86,  7, 44, 74,
       67, 62, 43, 72, 95, 38,  4, 11, 18, 91,  2, 40, 27, 55, 16],
      dtype=int32)

In [62]:
idx = np.argsort(arr8.flatten())
arr8.flatten()[idx[-5:]]

array([95, 96, 97, 98, 99], dtype=int32)

In [63]:
np.argsort(arr8)

array([[3, 0, 8, 9, 2, 6, 7, 4, 5, 1],
       [4, 3, 6, 0, 2, 5, 8, 1, 7, 9],
       [6, 5, 7, 0, 4, 1, 8, 2, 9, 3],
       [4, 1, 6, 7, 8, 5, 3, 0, 9, 2],
       [0, 2, 5, 7, 6, 3, 9, 8, 4, 1],
       [3, 5, 7, 4, 1, 6, 0, 9, 2, 8],
       [2, 1, 3, 7, 4, 8, 6, 5, 9, 0],
       [1, 0, 6, 3, 7, 2, 8, 9, 4, 5],
       [2, 7, 3, 6, 5, 8, 4, 1, 9, 0],
       [5, 1, 2, 9, 3, 7, 0, 6, 8, 4]])